language: node_js
node_js:
- 12
before_install:
- npm install -g npm
script:
- npm install
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Cd2ChBKsf1NVODCrwkXuUIfyKksZo5qOA7z4WWGLGNdHiiDZa83MVhCY8jOLooV/zrSJfYRGcx3vA7EQCcLJvrA/9ViponHmOtHRq2uskPsVNcq/ugoPMHycSHMGAtZd52F2YKFWM0OFb0O7hzecZ4jJ6AfJMP00avTgJeM5PdHLz7HL1sB3Zwx1pxZMOB+9viWkvYK1h2ETaAz+WLE1GgbzE21E9yMPAAK9wPVZWwekAqQxQQTeQeLvxOpt+1tiUOXeA0sfGTjxUWHOozxREKOx/VecJBFmnVORJDs3iTS/Wg5ZTS3T938qpJhbFYCsNTuJsxxGimn2ofhrgwCGVG2m3FnaMAV9mZKpKPhqcpAgXI8I2JyzBKfvVCjUTsLiRb5Cvf0Bz+XL1W4ZEz9cpFiVofNsn1SYoFRqP4qWoaoOr6YVCAS5UO49cW7rPxQ8u+VA452h7BTJ6DTlGEBcXjeEOl7ubLSqdRBkGyi0B2BsGn7U6HLsshAUJF2DHMhRaIrg1bmi4b2FcedpvO8Yd5KsKUxXPMw9LFc5r1/y+CrphADjbKZS9Ibfj0eH151oIhKfJDUbszKHwAIrPO/rCjJwtktcRyFUlSxDny5qvdNS0OMKF8r7O4H9DmTyxymTtilrb8SKpeZodz6hIdw3tVo4dUbqsSZZkwMmnkLNdDE=
  app: nd-travis-heroku-test
  on:
    repo: Holajuwon/nd-travis-heroku-test
