language: node_js
node_js:
- 12
before_install:
- npm install -g npm
script:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: YTurdTc1dRsJhdauBCKuVxVEIkODZZwp+dRFEoVcmFd82OurP6cwIAyJihtOTnzotP+DbQH53pTl2Wjh0eCee3Me6ag/Wj1qXMjupgFqo8yYd7EFD+fuVl70ziLYeIIAzDVqXTfTuFJSiygxTObrC9kDK7bzDkEmYe0mB5ilIF6CwktGHMhxpeo6X0ZdFJ1cswgNXBdi33zpXt/FWCnKFfvqERpKru3W8bL8temcirPDzBc5uGwqp9wgor+SdMOtOgdbHyFSO+UxTpm5tLA5XfTdWLSPVmGgMThjl2qsLjkG2atVtFu83AfivqE6zwuZ/CDAGCcohoUvBjkRikmcUQuNnhBgwbz9bSPw/j3Jgju9OWZl801cmvoDMzxsAWKK89JqOp9y6sQq9GPWaYC/Iien43Qx2A2yM39KIKPit5XVCC6C227+l+zf3i/K2gmDj7WTs8sw8vvSwFCfJGSgqtYjxnRtQW7JjGxgxeh40SZNP4Xlch7aVb579TqGBMbbF8b7274Fdmx2GkPHSwFRvBYbKE7voNOCQwYjq5vfRq6U619njLlCYRHHf/mVh3PgcFBqD54AveC18JGKRTBq2m6oFSBU50EQw5XHpktENoSoYRWcJS+UVs8XbBhW1ddS+He6JtB+nj1spDOM6pA+es4nEXGA8OjHNgklWrKU8NQ=
  app: nd-travis-heroku-test
  on:
    repo: Holajuwon/nd-travis-heroku-test
