language: node_js
node_js:
- 12
before_install:
- npm install -g npm
script:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: RgMsSQWl7u1eAHAvqlrv8q8pVwDcGhhPOy3omOq9kcBvrC+up/wJz5HSTGcypgvilH8CB1jnK36zw38FOcfz3QOuDPovGHLZb4Al4jIvdgwIVxT0WjQgcYXTHeQRa8xS4iguqs3d/7byhDua5R6rXl07XxIN6mMrDvVxu0e9Yh090ktRt9UsMrH/RlOlO7CJxA4T5XSkwRILL3LHCZ4aIs3NqvLIJSzUoHCllmf8KgBQfQD+FjkCfWaR71nYtDOJLHIVJsANyeUA6t92tZlMAt1HjvIq33ZRrMAGjf8Amq9Xd4JoBNUI2z7oLXiwKRKfbEnY+PNKXxz99SPgqdmHhVHVXW9LeHnyP3z/r8WtK45RZcJYCSZ4MFfPDq5tBSG0tHaYtJPF78uYN5Fve79///iBh3Wqw9Imtv8NAhvjgvdVP7IB/lCDx+v2G+fVoHPZlmJHD6eUCRF16ZnQSz9u+4TCc/N6IjhAM+wZAkMP7DYOdHk/u9SVVapWPrlbFCco9G9KsCm9Ij82AKFmed8TILp+qfRPEZ9a3urpNrtonvteRRQdkmG1Of/a5kL726cWMCjxHbduxW1/lxq9AwXqN3M/x2abPRIZDnTkXH0Uo0xyBrOzqDF05MCIHdH5CykdXdKZXMxE1KxaVLuJ1QZBEQdJ9YdvVL7TF38sF1G1gvg=
  app: nd-travis-heroku-test
  on:
    repo: Holajuwon/nd-travis-heroku-test
